# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/git-lfs-3.4.0-ha770c72_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/_tflow_select-2.1.0-gpu.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2023.11.17-hbcca054_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-cudart-11.7.99-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-cupti-11.7.101-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvrtc-11.7.99-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvtx-11.7.91-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-10.1.243-h6bb024c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2021.4.0-h06a4308_3561.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/ld_impl_linux-64-2.40-h41732ed_0.conda
https://conda.anaconda.org/nvidia/linux-64/libcublas-11.10.3.66-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufft-10.7.2.124-h4fbf590_0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufile-1.6.1.9-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcurand-10.3.2.106-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusolver-11.4.0.1-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusparse-11.7.4.91-0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/libgfortran5-11.2.0-h1234567_1.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnpp-11.7.4.75-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnvjpeg-11.8.0.2-0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libstdcxx-ng-12.2.0-h46fd767_19.tar.bz2
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-libraries-11.7.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cudnn-7.6.5-cuda10.1_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cupti-10.1.168-0.conda
https://conda.anaconda.org/anaconda/linux-64/libgfortran-ng-11.2.0-h00389a5_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libgomp-12.2.0-h65d4601_19.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2021.4.0-h06a4308_640.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-runtime-11.7.1-0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libblas-3.9.0-12_linux64_mkl.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libcblas-3.9.0-12_linux64_mkl.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libgcc-ng-12.2.0-h65d4601_19.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/pytorch-cuda-11.7-h778d358_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.0-h5eee18b_0.conda
https://conda.anaconda.org/anaconda/linux-64/fftw-3.3.9-h27cfd23_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.2.1-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.2.1-h295c915_3.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/icu-58.2-hf484d3e_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/keyutils-1.6.1-h166bdaf_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/lame-3.100-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libbrotlicommon-1.0.9-h166bdaf_8.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.8-h7f8727e_5.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libexpat-2.5.0-hcb278e6_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libffi-3.3-h58526e2_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h7f8727e_2.conda
https://conda.anaconda.org/conda-forge/linux-64/libnsl-2.0.0-h7f98852_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libtasn1-4.19.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libunistring-0.9.10-h27cfd23_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libuuid-2.38.1-h0b41bf4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.2.4-h5eee18b_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libzlib-1.2.13-h166bdaf_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/ncurses-6.3-h27087fc_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/nspr-4.35-h27087fc_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openh264-2.1.1-h4ff587b_0.conda
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1w-hd590300_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/pcre-8.45-h9c3ff4c_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/pthread-stubs-0.4-h36c2ea0_1001.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/xorg-libxau-1.0.11-hd590300_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/xorg-libxdmcp-1.1.3-h7f98852_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/xz-5.2.6-h166bdaf_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/expat-2.5.0-hcb278e6_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libbrotlidec-1.0.9-h166bdaf_8.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libbrotlienc-1.0.9-h166bdaf_8.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libedit-3.1.20191231-he28a2e2_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libevent-2.1.12-h8f2d780_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libidn2-2.3.4-h5eee18b_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libsqlite-3.42.0-h2797004_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libxcb-1.15-h0b41bf4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nettle-3.7.3-hbbd107a_1.conda
https://conda.anaconda.org/conda-forge/linux-64/perl-5.32.1-4_hd590300_perl5.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/readline-8.2-h8228510_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/tk-8.6.12-h27826a3_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/zlib-1.2.13-h166bdaf_4.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/boost-cpp-1.70.0-ha2d47e9_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/brotli-bin-1.0.9-h166bdaf_8.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.69.1-h4ff587b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/gnutls-3.6.15-he1e5248_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.6-h3ffc7dd_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/krb5-1.19.3-h3790be6_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libllvm10-10.0.1-he513fc3_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-3.20.3-he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.14-h74e7548_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/nss-3.89-he45b914_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/sqlite-3.42.0-h2c6b66d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.2-ha4553b6_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/brotli-1.0.9-h166bdaf_8.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.1-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libclang-10.0.1-default_hb85057a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-12.9-h16c4e8d_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.4.0-hecacb30_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxkbcommon-1.0.1-hfa300c1_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxslt-1.1.35-h4e12654_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.7.13-haa1d7c7_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/absl-py-1.3.0-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/astor-0.8.1-py37h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2023.11.17-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/colorama-0.4.6-pyhd8ed1ab_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/cycler-0.11.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/fontconfig-2.14.2-h14ed4e7_0.conda
https://repo.anaconda.com/pkgs/main/noarch/gast-0.5.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.1-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.2.4-h11a3e52_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.1-py37h7f8727e_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch/munkres-1.0.7-py_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/packaging-23.1-pyhd8ed1ab_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/ply-3.11-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/protobuf-3.20.3-py37h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.9.0-py37h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/pyparsing-3.0.9-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py37_1.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/python_abi-3.7-2_cp37m.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/pytz-2023.3-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/termcolor-2.1.0-py37h06a4308_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/toml-0.10.2-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.3.0-py37h06a4308_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/wheel-0.40.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wrapt-1.14.1-py37h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.11.0-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py37h74dc2b5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/google-pasta-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/grpcio-1.42.0-py37hce63b2e_0.conda
https://conda.anaconda.org/bioconda/linux-64/hhsuite-3.3.0-py37pl5321h675a0cb_6.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-4.11.3-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.2-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.4-py37h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py37h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-9.4.0-py37h6a678d5_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/python-dateutil-2.8.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/pytorch-1.13.0-py3.7_cuda11.7_cudnn8.5.0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/qt-main-5.15.2-h327a75a_7.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/setuptools-59.8.0-py37h89c1867_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/sip-6.6.2-py37hd23a5d3_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/tornado-6.2-py37h540881e_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/tqdm-4.65.0-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/werkzeug-2.2.2-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py37h27cfd23_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-39.0.1-py37h9ce1e76_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/joblib-1.2.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/markdown-3.4.1-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.21.5-py37ha15fc14_3.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/pip-23.1.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt5-sip-12.11.0-py37h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-webengine-5.15.9-hd2b0992_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.0.0-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtwebkit-5.212-h4eab89a_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.15.7-py37h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.14-py37h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.28.1-py37h06a4308_0.conda
https://conda.anaconda.org/anaconda/linux-64/biopython-1.78-py37h7f8727e_0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/scipy-1.7.3-py37h6c91a56_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/h5py-3.7.0-py37h737f45e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.1-py37hd3c417c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py37h51133e4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.21.5-py37h6c91a56_3.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/boost-1.70.0-py37h9de70de_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/keras-applications-1.0.8-py_1.conda
https://repo.anaconda.com/pkgs/main/noarch/keras-preprocessing-1.1.2-pyhd3eb1b0_0.conda
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/matplotlib-base-3.5.3-py37hf395dca_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/pandas-1.2.3-py37hdc94413_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/scikit-learn-0.21.3-py37hcdab131_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tensorboard-1.14.0-py37hf484d3e_0.conda
https://conda.anaconda.org/pytorch/linux-64/torchaudio-0.13.0-py37_cu117.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchvision-0.14.0-py37_cu117.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64/blast-2.5.0-hc0b0e79_3.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/matplotlib-3.5.3-py37h89c1867_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/networkx-2.6.3-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/pyg/linux-64/pyg-2.3.1-py37_torch_1.13.0_cu117.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-base-1.14.0-gpu_py37he45bfe2_0.conda
https://conda.anaconda.org/dglteam/label/cu117/linux-64/dgl-1.1.1.cu117-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tensorflow-estimator-1.14.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-1.14.0-gpu_py37h74c33d7_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-gpu-1.14.0-h0d30ee6_0.conda
